### ISSUE TITLE
Test Certs are invalid, getting "SSLV3_ALERT_HANDSHAKE_FAILURE" Error

### ISSUE THREAD

**Issue by puneetshanbhag** [adplabs/adp-connection-python#12]
Test Certificates provided in the library are invalid , when we try the sample code provided in the documentation we are getting "**SSLV3_ALERT_HANDSHAKE_FAILURE**"

Logs:-
DEBUG:root:creating base config class
DEBUG:root:Initializing Config Object
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): iat-api.adp.com:443
Unexpected error: (<class 'requests.exceptions.SSLError'>, SSLError(MaxRetryError("HTTPSConnectionPool(host='iat-api.adp.com', port=443): Max retries exceeded with url: /auth/oauth/v2/token (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))",),), <traceback object at 0x0000000003EA2948>)

**Comment by ADPMarketplace** [comment]
Please try again with the new certificates.
