### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by emekanw** [adplabs/adp-connection-python#3]
Followed the Example and executed `python -u sampleApp.py`

went to the url `http://localhost:8889/`

When I click `Connect to the Authorization Code App` I get the error below:

```127.0.0.1 - - [05/Dec/2016 18:08:21] "GET /authorization_code HTTP/1.1" 302 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iat-api.adp.com
Unexpected error: (<class 'requests.exceptions.SSLError'>, SSLError(SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),),), <traceback object at 0x10e957a28>)
```

What am i missing?

**Comment by ADPMarketplace** [comment]
Will you please let us know what version of Python and OS environment you are using?

**Comment by emekanw** [comment]
OS X EL Capitan
Python 2.7.11

**Comment by emekanw** [comment]
Problem seems to be coming from `requests.post()` SSL Cert Verification. It works if verify is False, obviously we want to verify to be True, which is the default value hence the issue. 

https://github.com/adplabs/adp-connection-python/blob/master/adp_connection/lib/adpapiconnection.py#L91-L97

https://github.com/adplabs/adp-connection-python/blob/master/adp_connection/lib/adpapiconnection.py#L188-L193

**Comment by ADPMarketplace** [comment]
The test endpoint (iat-api.adp.com) uses an ADP CA ssl certificate. This is not the case in our production environment and the default value will work. For test environment, please use the attached CA chain file and use verify to point to the location of this file on your system. In an upcoming update to the API libraries, we will include this as part of the sample and also allow setting the verify value.

**Comment by emekanw** [comment]
> please use the attached CA chain file 

did you mean to attach a file?

**Comment by ADPMarketplace** [comment]
Please let us know if the email on your profile is a good one to use to send a file.

**Comment by emekanw** [comment]
oh ok thanks. It is. I grabbed the file from your ruby example which works.
