### ISSUE TITLE
Needs updating for Python3

### ISSUE THREAD

**Issue by ducksauz** [adplabs/adp-connection-python#5]
Python 2.7's [EOL in 2020](https://legacy.python.org/dev/peps/pep-0373/) is approaching. Would be nice if this library were updated with Python3 support. I'm writing new code now and doing it in Python 3.7, which mean that I'm not using this library.

**Comment by ADPMarketplace** [comment]
Checking with internal team.

**Comment by ADPMarketplace** [comment]
Hi,
We're working on this and mostly will be updating the version very soon. Will keep you posted with the update.

Thanks,
Mahesh

**Comment by ADPMarketplace** [comment]
Hi,
Our team is working on it to update the python version. Will keep you posted with the latest update.

Thanks,
Mahesh

**Comment by KrunchMuffin** [comment]
This is closed without updating? Is this ever going to be done? I can't do new projects with ancient 2.7.

**Comment by kskumar** [comment]
@ADPMarketplace instead of "working to update the python version," you could just merge #4, which contains the necessary changes

@KrunchMuffin you can manually patch the changes from #4 to use this library with 3.x
