### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by TannerHolle** [adplabs/adp-connection-python#9]
I am getting an error saying "Request did not provide the required two-way TLS certificate."  How can I include a certificate in my python request to let me retrieve the information?

![ErrorMessage](https://user-images.githubusercontent.com/43889942/75077339-a9a6f780-54bf-11ea-96d5-f1b6708e321b.png)

**Comment by ADPMarketplace** [comment]
Hi, 

Please include certificates in your token request and any subsequent feature requests.
